### ISSUE TITLE
UI text is too small to read.

### ISSUE THREAD

**Issue by andybak** [ttddee/Cascade#45]
Laptop with 2560x1600 15" display. Windows UI scaling is set to 150% but Cascade seems to ignore this setting.

I have reading glasses but they are far from sufficient to make this usable for me. No other app I've come across suffers from this problem to anything like the same degree.

**Comment by ttddee** [comment]
Hi!

Thanks for the feedback! I haven't tested higher resolutions yet but will get to that asap.

**Comment by ttddee** [comment]
Here is a build with high-DPI scaling enabled: https://github.com/ttddee/CascadeExtra/raw/main/Cascade-Image-Editor-Win64-v0-2-0-dev-69ad806.zip

I have tested it on a laptop at 3840x2160 and it looks OK-ish.

How does it look for you?

**Comment by ttddee** [comment]
@andybak The [latest release](https://github.com/ttddee/Cascade/releases/tag/v0.2.0-alpha) includes scaling for high-DPI screens. Are you able to test this on your end?

**Comment by andybak** [comment]
That's much better.

**Comment by ttddee** [comment]
I'll close this one. If there are issues with the scaling on your screen, please open a new issue. Thanks!
