### ISSUE TITLE
Failed to Initialise Vulkan

### ISSUE THREAD

**Issue by jannuary** [ttddee/Cascade#5]
First of all, neat project, really excited to see where it will go in the future!

I'm trying to launch the latest appimage, which gives a "Failed to Initialise Vulkan" error with an empty `cascade.log` on Fedora Workstation 33 with an AMD Radeon RX 560 (POLARIS11, DRM 3.40.0, 5.10.7-200.fc33.x86_64, LLVM 11.0.0), both on X and Wayland.
Here's the output of `vulkaninfo`, if that is of any use. [vulkaninfo.txt](https://github.com/ttddee/Cascade/files/5825961/vulkaninfo.txt)

**Comment by ttddee** [comment]
Hi! Thanks for your feedback!

In order to find out what's going on I think I will have to add some more logging code to get at least some information on where things go wrong. 

Can you run other Vulkan applications fine? For example [this](https://github.com/SaschaWillems/VulkanCapsViewer)?

**Comment by jannuary** [comment]
> Can you run other Vulkan applications fine? For example this?

That works, but only on X11.

**Comment by jannuary** [comment]
Hm, exporting `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` and rebooting seems to have fixed the issue
