### ISSUE TITLE
Improve qmake OS detection on Linux

### ISSUE THREAD

**Issue by ttddee** [ttddee/Cascade#63]
Right now qmake is only checking if we are on Windows or Linux. Since different dependencies are available on different Linux flavors, checking for the distribution we could avoid compiling unnecessary packages.

To check the distro in qmake something like this could work:

```
ARCH = $$system(cat /proc/version | grep -o Arch) 
UBUNTU = $$system(cat /proc/version | grep -o Ubuntu) 

contains( ARCH, Arch): 
{     
   do stuff
} 
contains( UBUNTU, Ubuntu): 
{     
   do other stuff
}
```

**Comment by Yaraslaut** [comment]
Assign me

**Comment by ttddee** [comment]
I have added a check to the [pro file](https://github.com/ttddee/Cascade/blob/master/Cascade.pro) to detect if we are on Ubuntu 18 LTS. Needed that for building the AppImages in Github Actions. That's how we could do it for other distros.
