### ISSUE TITLE
Title bar icon missing in Linux

### ISSUE THREAD

**Issue by Skalt711** [ttddee/Cascade#68]
The title bar icon defaults to a generic X11 icon. I expect the Cascade title bar icon similar to Cascade.pro one or (attached to the issue) Cascade.png inside the AppImage.
I use KDE.
I peaked at the code and it looks like there is no setWindowIcon that requests a .png image to set an icon.
![Cascade](https://user-images.githubusercontent.com/38584050/169576335-fea1a818-a195-400b-a8a4-13d7c2df0ac0.png)

**Comment by ttddee** [comment]
Fixed. Thanks!

**Comment by Skalt711** [comment]
The title bar icon commit fixed the issue!
![Screenshot_20220521_155253](https://user-images.githubusercontent.com/38584050/169652447-65cb5fd8-8cdc-4651-8bcb-5e6b6485be91.png)
