### ISSUE TITLE
This project has been abandoned

### ISSUE THREAD

**Issue by ekliptik** [ttddee/Cascade#80]
Just a disclaimer. While buildable (on my machine it required some trivial modifications due to deprecated APIs, though that's because of nix somehow forcing me to use Qt6) you won't get the experience you can see in the screenshots, since the project was abandoned in the middle of some modifications. The "ISV shader" nodes (I don't understand graphics) are missing and all you get are two test types of nodes. See git log of src/mainmenu.cpp

If you're here because you're struggling to get it to a usable state: as an alternative, I will consider looking into natron. If you want to revive this project, go through logs and find a tag that's somewhat usable, and fork from there.

Also, the linked Discord is not just inactive, but some children have ran in to spew hateful non-sense

**Comment by ttddee** [comment]
Hi, yes my bad, life got in the way.

If you want to build the version from the screenshots, check out this tag: https://github.com/ttddee/Cascade/tree/v0.2.0-alpha

I'll see if I can fix the discord.
